[dev]
   command = "yarn dev"

[build]
  command = 'yarn generate'
  publish = 'dist'
	
	# Always build, builds are no longer expensive
  ignore = "exit 1"

<%_ if (shopify) { _%>
# Allow static-data to pass CORS check from shopify-theme
[[headers]]
  for = '/data/*'
    [headers.values]
    Access-Control-Allow-Origin = '*'
<%_ } _%>
