field: ec56af06-33ca-4f16-a73a-89f37d116142 # SEO
fieldLayouts:
  c2325b5e-c50c-4070-97a3-c7e5dab5e0ce:
    tabs:
      -
        elements:
          -
            fieldUid: 6fc04ae2-bc2a-4021-aed9-24b0a9a6ec9e # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d8e7d38f-9b07-4e45-bb42-946070c16724 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c56835da-8ddd-4bce-b6fc-a8f0de829635 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8738446a-ff18-4110-9a8e-29c2f68ff4de # Robots
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f2c0a6d4-dbae-4a40-aaf5-9ba8f676f926 # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6fc04ae2-bc2a-4021-aed9-24b0a9a6ec9e: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: metaTitle
    instructions: 'If empty, the Entry Title will be used.'
    name: Title
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8738446a-ff18-4110-9a8e-29c2f68ff4de: # Robots
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: robots
    instructions: ''
    name: Robots
    searchable: false
    settings:
      multi: true
      options:
        -
          __assoc__:
            -
              - label
              - 'noindex - Don''t index page'
            -
              - value
              - noindex
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'nofollow - Don''t follow links on page or pass along any link equity'
            -
              - value
              - nofollow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'noarchive - Don''t show a cached link to this page'
            -
              - value
              - noarchive
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Checkboxes
  c56835da-8ddd-4bce-b6fc-a8f0de829635: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: metaImage
    instructions: 'Recommended 1200 x 627'
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:d507d988-558f-49c4-b53b-471a38e1d525' # Assets
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: thumbs
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:d507d988-558f-49c4-b53b-471a38e1d525' # Assets
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d8e7d38f-9b07-4e45-bb42-946070c16724: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: metaDescription
    instructions: 'Try to keep below 160 characters.'
    name: Description
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f2c0a6d4-dbae-4a40-aaf5-9ba8f676f926: # Canonical URL
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: canonicalUrl
    instructions: 'If present, this will override the default behavior of using the current URL as the canonical value.'
    name: 'Canonical URL'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
