field: 4231471d-4063-4b18-a8b0-f8927cc22cb9 # Buttons
fieldLayouts:
  8920f8d5-f76d-42fa-843d-13ca15d92209:
    tabs:
      -
        elements:
          -
            fieldUid: 81277674-1ae1-4c6c-b945-9b6e2d433cc3 # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dab32934-4eef-4bf2-afaa-b74bbe1a5a85 # URL
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  81277674-1ae1-4c6c-b945-9b6e2d433cc3: # Label
    contentColumnType: text
    fieldGroup: null
    handle: label
    instructions: ''
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dab32934-4eef-4bf2-afaa-b74bbe1a5a85: # URL
    contentColumnType: string(255)
    fieldGroup: null
    handle: to
    instructions: 'Use an absolute path (ex: "/contact") for internal links.'
    name: URL
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
        - tel
        - email
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
