field: ba5dd543-6799-42ff-a37f-8d8431e32e13 # Responsive Video
fieldLayouts:
  45f60c2d-4204-415e-8a92-f386be29ded8:
    tabs:
      -
        elements:
          -
            fieldUid: af8f5c62-eeb2-49b5-b0c4-bcc2355159f5 # Landscape Device
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a83bcc1-2811-4d1b-99f4-aadb1891920a
            warning: null
            width: 100
          -
            fieldUid: 78cb78c4-082c-487f-bd57-ce5b32eb2bb9 # Portrait Device
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bf88aa49-a8fa-4a0e-a922-fdd5e3eaf4b5
            warning: null
            width: 100
        name: Content
        uid: f2669def-c1e1-4874-b44f-a0d71189e26c
fields:
  78cb78c4-082c-487f-bd57-ce5b32eb2bb9: # Portrait Device
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: portrait
    instructions: 'This video will be shown on portrait aspect ratio viewports, like mobile browsers.'
    name: 'Portrait Device'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - video
      defaultUploadLocationSource: 'volume:c9c87263-ba15-47e4-bb1b-002b231b2f98' # Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c9c87263-ba15-47e4-bb1b-002b231b2f98' # Assets
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  af8f5c62-eeb2-49b5-b0c4-bcc2355159f5: # Landscape Device
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: landscape
    instructions: 'This video will be shown on landscape aspect ratio viewports, like desktop browsers.'
    name: 'Landscape Device'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - video
      defaultUploadLocationSource: 'volume:c9c87263-ba15-47e4-bb1b-002b231b2f98' # Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c9c87263-ba15-47e4-bb1b-002b231b2f98' # Assets
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
