changedFieldIndicator: null
field: 7b717a9b-592f-4c43-bbb2-e644948cb7d4 # Responsive Image
fieldLayouts:
  fbfbc3d8-603a-4e88-96a1-a349eb63d9a7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: de97ce0f-548b-4114-8d77-fbf9a3b6c2c2 # Landscape Browser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bfb4f801-309f-4d21-8df6-3fba2edd5590
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 87d83354-b0a5-4892-bca2-8837f965151b # Portrait Browser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a14aaba3-43df-4359-8b70-e01f29173ed7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 93c4d585-c537-44c6-8b45-d0de20592f22
        userCondition: null
fields:
  87d83354-b0a5-4892-bca2-8837f965151b: # Portrait Browser
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: portrait
    instructions: 'This image will be shown on portrait aspect ratio viewports, like mobile browsers.'
    name: 'Portrait Browser'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:c9c87263-ba15-47e4-bb1b-002b231b2f98' # Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: thumbs
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c9c87263-ba15-47e4-bb1b-002b231b2f98' # Assets
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  de97ce0f-548b-4114-8d77-fbf9a3b6c2c2: # Landscape Browser
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: landscape
    instructions: 'This image will be shown on landscape aspect ratio viewports, like desktop browsers.'
    name: 'Landscape Browser'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:c9c87263-ba15-47e4-bb1b-002b231b2f98' # Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: thumbs
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:c9c87263-ba15-47e4-bb1b-002b231b2f98' # Assets
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
