dateModified: 1626020454
email:
  fromEmail: cms@send.bukwild.com
  fromName: CMS
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: tls
    host: smtp.mailgun.org
    password: $EMAIL_PASSWORD
    port: '587'
    timeout: '10'
    useAuthentication: '1'
    username: cms@send.bukwild.com
  transportType: craft\mail\transportadapters\Smtp
plugins:
  colorit:
    edition: standard
    enabled: true
    licenseKey: FHU3QUJ1HMLSM73ALBZX7SQD
    schemaVersion: 1.0.3
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: ''
      cssFile: /cp.css
  cp-js:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalJs: ''
      jsFile: /cp.js
  dashboard-begone:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  neo:
    edition: standard
    enabled: true
    licenseKey: ORSYW1SVA20KHNLTUWR1NC8G
    schemaVersion: 2.9.11
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  sentry:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      clientDsn: $SENTRY_DSN
      enabled: '1'
      environment: $ENVIRONMENT
      excludedCodes: '404'
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  webhooks:
    edition: standard
    enabled: true
    schemaVersion: 2.3.1
system:
  edition: pro
  live: true
  name: CMS
  retryDuration: null
  schemaVersion: 3.6.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: ''
  photoSubpath: null
  photoVolumeUid: d507d988-558f-49c4-b53b-471a38e1d525 # Assets
  requireEmailVerification: true
  suspendByDefault: false
