dateModified: 1655345499
elementSources:
  craft\elements\Asset:
    -
      disabled: false
      key: 'volume:c9c87263-ba15-47e4-bb1b-002b231b2f98' # Assets
      tableAttributes:
        - size
        - dateModified
        - link
      type: native
    -
      disabled: true
      key: 'folder:4c9ee7de-d12f-46db-8baa-648424a9e7f1'
      tableAttributes:
        - size
        - dateModified
        - link
      type: native
  craft\elements\Entry:
    -
      disabled: true
      key: '*'
      tableAttributes:
        - section
        - dateUpdated
      type: native
    -
      heading: Pages
      type: heading
    -
      disabled: false
      key: 'section:186a5336-eaea-4df2-bfc8-e5a20da010f3' # Towers
      tableAttributes:
        - uri
      type: native
    <%_ if (shopify) { _%>
    -
      disabled: false
      key: 'section:98186665-a0ee-4abe-9c44-3a1736939a1d' # Products
      tableAttributes:
        - uri
      type: native
    <%_ } _%>
    -
      heading: Elements
      type: heading
    -
      disabled: false
      key: 'section:98dcc5b4-aeb9-4b83-9b22-930f801ec61a' # Reusable Sections
      tableAttributes:
        - dateUpdated
      type: native
    -
      heading: Functionality
      type: heading
    -
      disabled: false
      key: 'section:10c8f63f-7625-41fd-af7e-563ca33f0864' # Redirects
      tableAttributes:
        - 'field:c1d660db-a389-457a-b8ab-61fd5253fca1' # Redirect - Code
      type: native
email:
  fromEmail: cms@send.bukwild.com
  fromName: CMS
  replyToEmail: null
  template: null
  transportSettings:
    encryptionMethod: tls
    host: smtp.mailgun.org
    password: $EMAIL_PASSWORD
    port: '587'
    timeout: '10'
    useAuthentication: '1'
    username: cms@send.bukwild.com
  transportType: craft\mail\transportadapters\Smtp
fs:
  spaces:
    hasUrls: true
    name: 'DigitalOcean Spaces'
    settings:
      bucket: $SPACES_BUCKET
      contentDisposition: ''
      endpoint: $SPACES_ENDPOINT
      expires: '1 years'
      keyId: $SPACES_API_KEY
      region: $SPACES_REGION
      secret: $SPACES_SECRET
      subfolder: cms
    type: vaersaagod\dospaces\Fs
    url: '@spacesBaseUrl'
meta:
  __names__:
    2d9687b3-b684-4874-a7a8-ab944ad8b8d1: SEO # SEO
    2e17b992-2242-41da-b88e-9e2a43c77c01: Video # Video
    2fd34dec-1616-4dfa-a937-862dd23bb8ed: Blocks # Blocks
    4a8ec7bb-bb8b-4e71-8473-8a1959ab8ee2: Wrapper # Wrapper
    4b677453-d75d-4b58-b417-d4d3a55abee2: Image # Image
    4bbcd477-ee45-4aaa-88f6-b71445edcaa4: 'Text Alignment' # Text Alignment
    5da73805-8b5d-48f2-a98e-796b61a49c7b: Title # Title
    5e038f76-3399-4dbc-a094-ccf1ce3d817b: Pages # Pages
    6ba1665a-8402-412e-9aa8-a32891d9ea15: Label # Label
    6f76a787-c809-43bc-afe5-bd95e815e131: 'URI Path' # URI Path
    7b717a9b-592f-4c43-bbb2-e644948cb7d4: 'Responsive Image' # Responsive Image
    7e90e7a7-1913-4abe-a281-eae317c58770: Layout # Layout
    8dad1526-e3d9-4d23-a5f0-a0515ccbb2ca: Copy # Copy
    008df272-719d-4314-91bd-46f97a05c1d7: Site # Site
    8f23a5bb-60fd-42cb-896e-50a2849a18be: Unorphan # Unorphan
    10c8f63f-7625-41fd-af7e-563ca33f0864: Redirects # Redirects
    24cdf41e-e940-436e-81e1-984ac9217753: 'Max Width' # Max Width
    37e178d0-caa3-4f07-ba8f-0622ccc5d9a5: Default # Default
    78cb78c4-082c-487f-bd57-ce5b32eb2bb9: 'Portrait Browser' # Portrait Browser
    83dfc50b-8fb9-4860-a023-412237984a08: 'Background Color' # Background Color
    84c82111-676d-4cc9-9d6a-37a167f8151a: Layout # Layout
    85a957c5-8697-4eb8-89a6-036725aa7411: Marquees # Marquees
    87d83354-b0a5-4892-bca2-8837f965151b: 'Portrait Browser' # Portrait Browser
    093c0f01-674f-4456-9f9f-c08e7043cc4d: 'Public Schema' # Public Schema
    95b29d64-fe33-4526-bee4-0570f4901a9b: 'Canonical URL' # Canonical URL
    98dcc5b4-aeb9-4b83-9b22-930f801ec61a: 'Reusable Sections' # Reusable Sections
    186a5336-eaea-4df2-bfc8-e5a20da010f3: Towers # Towers
    9745b1d2-5506-4a0f-b23f-dff4068bc084: Common # Common
    19063645-1c73-4f2a-97d6-d09ec798bd83: Site # Site
    61011763-c00b-4946-8e21-10ac1b6720c8: Basics # Basics
    98186665-a0ee-4abe-9c44-3a1736939a1d: Products # Products
    a7ca55f8-9c66-4ebf-88ec-137e2917eefb: Robots # Robots
    a739e22f-8e56-4431-acf9-42b1c1cfbf02: 'Default SEO' # Default SEO
    acc2ba21-dae4-47cc-bf46-870d7d429882: 'Reusable Section' # Reusable Section
    acc3eb47-55fc-4174-9a80-46bbd841f2d9: Buttons # Buttons
    acf3ce17-0ce2-4643-a67f-0aad408e8d9f: Default # Default
    af8f5c62-eeb2-49b5-b0c4-bcc2355159f5: 'Landscape Browser' # Landscape Browser
    b9fb7e0c-d670-46e6-9f22-0fcbf74c76e7: Description # Description
    b5171329-a8e7-45c1-973c-d81ad60226a4: URL # URL
    ba5dd543-6799-42ff-a37f-8d8431e32e13: 'Responsive Video' # Responsive Video
    bd321f03-7ec9-486f-bc08-b02d37378f85: Spacing # Spacing
    bd919004-224d-4697-841d-bd8e0100e320: Text # Text
    bfd00e87-2045-4dad-ad01-da134ff74be6: 'Balance Text' # Balance Text
    c1d660db-a389-457a-b8ab-61fd5253fca1: 'Redirect - Code' # Redirect - Code
    c6c660ef-7571-4040-934a-8f9b9f0f11b4: 'Simple Marquee' # Simple Marquee
    c9c87263-ba15-47e4-bb1b-002b231b2f98: Assets # Assets
    ca292f2e-a489-4abf-8bfd-a37201b553c2: 'Full WYSIWYG' # Full WYSIWYG
    cd1175f4-00b9-446c-8048-4cbadb8bd243: Entries # Entries
    d9ec0e61-1044-4136-b7d7-6b9368827012: Product # Product
    db1453d6-d8c4-4e12-8320-1481643509c2: 'Redirect - From' # Redirect - From
    de97ce0f-548b-4114-8d77-fbf9a3b6c2c2: 'Landscape Browser' # Landscape Browser
    df38411b-18a5-4003-84aa-4143bd357605: 'Public Schema' # Public Schema
    dfe0196e-d542-4e68-a7fd-a1f51a3dd307: Assets # Assets
    e4cc7576-8cbb-4cbf-b61d-01124cc26236: Spacer # Spacer
    e4e747fe-6148-48f0-8a20-ef0767f3038f: 'Media Asset' # Media Asset
    e91a3004-6bc6-456d-a8fd-886f0a02488c: Text # Text
    ec5c130f-db1a-4e88-9e99-2ccad068c525: Image # Image
    ed10e046-ed60-4917-85e1-454ba5a5e0d0: Redirects # Redirects
    ef5c7247-23cf-41ec-b422-164deb7db9b3: 'Reusable Section' # Reusable Section
    f086dead-b963-4695-b991-70f21fa4f309: 'Redirect - To' # Redirect - To
    fd461696-8956-45eb-810f-34434625242b: Redirects # Redirects
plugins:
  colorit:
    edition: standard
    enabled: true
    licenseKey:
    schemaVersion: 1.0.3
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: ''
      cacheBusting: true
      cssFile: /cp.css
  cp-js:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalJs: ''
      cacheBusting: true
      jsFile: /cp.js
  dashboard-begone:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  neo:
    edition: standard
    enabled: true
    licenseKey:
    schemaVersion: 3.0.4
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  sentry-sdk:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  webhooks:
    edition: standard
    enabled: true
    schemaVersion: 2.4.0
system:
  edition: pro
  live: true
  name: "<%= name %>"
  retryDuration: null
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
