dateModified: 1641583661
email:
  fromEmail: cms@send.bukwild.com
  fromName: CMS
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: tls
    host: smtp.mailgun.org
    password: $EMAIL_PASSWORD
    port: '587'
    timeout: '10'
    useAuthentication: '1'
    username: cms@send.bukwild.com
  transportType: craft\mail\transportadapters\Smtp
meta:
  __names__:
    1a4b6751-b39b-4889-a185-e55df4e88fdb: Text # Text
    1ac617c7-6c7b-4a88-9a21-da83b6fb9db7: 'Text Alignment' # Text Alignment
    2a3e1dff-e96a-4ac1-8a6e-7eed68dfaa4e: 'Max Width' # Max Width
    2aca8c17-9c27-4bf0-9e7a-3f045b767d2a: Landscape # Landscape
    2f43c4ca-6ee6-4e49-9dc2-286e151ea6b0: 'Responsive Video' # Responsive Video
    6a560d02-778f-4c45-ba9b-8d733af642a2: Towers # Towers
    6cf89d15-da1d-4624-9120-c33ada5df8d4: Products # Products
    6fc04ae2-bc2a-4021-aed9-24b0a9a6ec9e: Title # Title
    08a01953-689a-4c68-ba66-569186fb3dc4: Video # Video
    8aa7b919-a245-4d28-836b-c599e4c99668: Assets # Assets
    8b15badc-af4c-44f7-a29d-0efff2f88cfc: Redirects # Redirects
    8cf6606b-c087-43db-8bd2-7f1ab7dd05ea: 'Balance Text' # Balance Text
    17a25a7a-86c8-4cfd-8a67-1bdc99703ecb: Local # Local
    032b2c9b-ff4b-4191-b76a-1ecad594e614: Products # Products
    33e6568b-9503-408d-bf85-4bc47b94633a: Portrait # Portrait
    50faa884-3981-42f7-a2b8-ab01cb2c3b6d: 'Default SEO' # Default SEO
    64a40ea1-96fa-4752-9374-94489dc97f96: 'Simple Marquee' # Simple Marquee
    80f5d10a-2957-4fe2-905a-2b34e5336acd: Redirects # Redirects
    086b5d2d-0b9e-4aff-b050-8b408c0eaeae: Basics # Basics
    210b8f7a-99b9-43ab-baba-f8b9d773b1c1: Layout # Layout
    350f57c3-762b-4c5a-b36c-864cbe3f5e4f: Text # Text
    415fec5d-10c8-449d-aa88-bff8dd05c4ee: Spacer # Spacer
    738a9619-9a83-40ff-b6ab-4156e9ff0790: 'Redirect - From' # Redirect - From
    3287fd8e-5dec-40b8-a8bb-1d81124f3db2: 'Redirect - Code' # Redirect - Code
    835037b1-cdf8-4cb3-880c-88910f020cd4: 'Full WYSIWYG' # Full WYSIWYG
    4231471d-4063-4b18-a8b0-f8927cc22cb9: Buttons # Buttons
    4723082f-b4ea-427d-8daa-882f0807e848: Towers # Towers
    8738446a-ff18-4110-9a8e-29c2f68ff4de: Robots # Robots
    51895965-9e46-40ff-a2a8-1f2ba17998db: 'Background Color' # Background Color
    81277674-1ae1-4c6c-b945-9b6e2d433cc3: Label # Label
    a50b9328-6e94-4a63-87c2-2c589e7bef20: Landscape # Landscape
    acc19cab-c962-4a2b-ab8b-c6a1a0e754ad: Redirects # Redirects
    b672bfcd-1595-4f91-86d8-2c7666326313: 'Public Schema' # Public Schema
    bcfdf78d-b3c4-455f-a438-44ead98881fd: 'Media Asset' # Media Asset
    be38339d-02bd-46cb-84ec-59dc7777fe3a: Common # Common
    c5d6747d-e70c-424e-beeb-cf1a49dd19d7: Marquees # Marquees
    c9b9f43f-3695-4d47-8d5c-5a2b8f08b2a9: Wrapper # Wrapper
    c9cbae83-6895-4b0f-a71c-658eb52c62c0: Image # Image
    c56835da-8ddd-4bce-b6fc-a8f0de829635: Image # Image
    c669537f-8a7f-4bde-962a-2e61c9b653c2: Site # Site
    cf3a29b0-7f16-4093-b6be-4340e57a3e24: 'Redirect - To' # Redirect - To
    d1b83162-d8d7-4409-b3e0-bb1be43bb297: Portrait # Portrait
    d6a44fe4-1500-4868-8559-30fd3b34625e: 'Responsive Image' # Responsive Image
    d8e7d38f-9b07-4e45-bb42-946070c16724: Description # Description
    d23a7d45-41cc-44ea-abdf-fac8d4ed95d8: Unorphan # Unorphan
    d507d988-558f-49c4-b53b-471a38e1d525: Assets # Assets
    dab32934-4eef-4bf2-afaa-b74bbe1a5a85: URL # URL
    ddd6b23b-385f-40b3-8454-5b03c755ce50: Towers # Towers
    e7e5af5d-802f-41c4-b63b-9ea56ce9b49a: Copy # Copy
    e79e3ac0-73ae-4b4d-95ea-6f87506b192c: Site # Site
    ec56af06-33ca-4f16-a73a-89f37d116142: SEO # SEO
    ec538ba2-0ee7-4b89-8110-5d94a9161e40: Layout # Layout
    f8f2273b-9131-4f32-856a-281379a96b75: 'URI Path' # URI Path
    f25955e8-9b37-4cf4-9101-2d6d2fa0a879: Spacing # Spacing
    fd4326a9-8ced-46ef-b0f2-c283f7482614: Blocks # Blocks
    f2c0a6d4-dbae-4a40-aaf5-9ba8f676f926: 'Canonical URL' # Canonical URL
plugins:
  colorit:
    edition: standard
    enabled: true
    licenseKey: FHU3QUJ1HMLSM73ALBZX7SQD
    schemaVersion: 1.0.3
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: ''
      cssFile: /cp.css
  cp-js:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalJs: ''
      jsFile: /cp.js
  dashboard-begone:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  dospaces:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  neo:
    edition: standard
    enabled: true
    licenseKey: ORSYW1SVA20KHNLTUWR1NC8G
    schemaVersion: 2.11.6
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  sentry:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      clientDsn: $SENTRY_DSN
      enabled: '1'
      environment: $ENVIRONMENT
      excludedCodes: '404'
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 2.2.1
  webhooks:
    edition: standard
    enabled: true
    schemaVersion: 2.3.1
system:
  edition: pro
  live: true
  name: CMS
  retryDuration: null
  schemaVersion: 3.7.7
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: ''
  photoSubpath: null
  photoVolumeUid: d507d988-558f-49c4-b53b-471a38e1d525 # Assets
  requireEmailVerification: true
  suspendByDefault: false
