#import "./pages/tower.gql"
<%_ if (shopify) { _%>
#import "./pages/product.gql"
<%_ } _%>

# Get all pages and their content for SSG
query getCraftPages(
	$site:[String]
	$section:[String!]
	$type:[String!]
	$uri:[String]) {

	entries(
		site:$site
		section:$section
		type:$type
		uri:$uri) {

		# Shared fields
		uri
		title

		# Page types
		...tower
		<%_ if (shopify) { _%>
		...product
		<%_ } _%>
	}
}
