#import "@cloak-app/craft/queries/fragments/default-seo.gql"

# Query Craft globals data
query getGlobals($site: [String]) {

	# Default (fallback) SEO values
	defaultSeo: globalSet(
		handle: "defaultSeo"
		site: $site) { ...defaultSeo }
}
