#import "@bkwld/cloak/fragments/craft/default-seo.gql"

# Query Craft globals data
query getGlobals {

	# Default (fallback) SEO values
	defaultSeo: globalSet(handle: "defaultSeo") { ...defaultSeo }
}
