#import "./fragments/blocks.gql"
#import "@cloak-app/craft/queries/fragments/seo.gql"

# Get all pages and their content for SSG
query getProduct(
	$site: [String]
	$uri: [String]) {

	entries(
		section: "products"
		site: $site
		uri: $uri) {

		id
		slug
		blocks { ...blocks }
		seo { ...seo }

	}
}
