#import "./fragments/blocks.gql"
#import "@cloak-app/craft/queries/fragments/seo.gql"

# Get page data
query getTower(
	$site: [String]
	$uri: [String]) {

	entry(
		section: "towers"
		site: $site
		uri: $uri) {
		...on towers_default_Entry {

			id
			title
			blocks { ...blocks }
			seo { ...seo }

		}
	}
}
