columnSuffix: null
contentColumnType: string(7)
fieldGroup: be38339d-02bd-46cb-84ec-59dc7777fe3a # Common
handle: backgroundColor
instructions: ''
name: 'Background Color'
searchable: false
settings:
  defaultColor: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
