columnSuffix: null
contentColumnType: string
fieldGroup: 5e038f76-3399-4dbc-a094-ccf1ce3d817b # Pages
handle: blocks
instructions: null
name: Blocks
searchable: false
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
