contentColumnType: string
fieldGroup: 4723082f-b4ea-427d-8daa-882f0807e848 # Towers
handle: blocks
instructions: ''
name: Blocks
searchable: false
settings:
  maxBlocks: ''
  maxLevels: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationMethod: all
  wasModified: false
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
