columnSuffix: sqlnjzjs
contentColumnType: string
fieldGroup: 7e90e7a7-1913-4abe-a281-eae317c58770 # Layout
handle: maxWidth
instructions: 'Applies a standardized width constraint.'
name: 'Max Width'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - 'Default - 1,280px wide'
        -
          - value
          - max-w
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Medium - 1060px wide, for an indented effect'
        -
          - value
          - max-w-medium
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Small - 750px wide, good for Copy blocks'
        -
          - value
          - max-w-small
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Full - 2,560px wide'
        -
          - value
          - max-w-full
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
