contentColumnType: string
fieldGroup: 80f5d10a-2957-4fe2-905a-2b34e5336acd # Redirects
handle: redirectCode
instructions: ''
name: 'Redirect - Code'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - '301 - Permanent'
        -
          - value
          - '301'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - '302 - Temporary'
        -
          - value
          - '302'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
