columnSuffix: null
contentColumnType: string
fieldGroup: dfe0196e-d542-4e68-a7fd-a1f51a3dd307 # Assets
handle: responsiveImage
instructions: 'Switch between image assets depending on the aspect ratio of the browser.  Typically, this is used to supply separate desktop (landscape) and mobile (portrait) images.  To use a single image for all cases, just upload a single image to either field.'
name: 'Responsive Image'
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 1233763492
  contentTable: '{{%stc_responsiveimage}}'
  fieldLayout: table
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: null
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
