columnSuffix: null
contentColumnType: string
fieldGroup: dfe0196e-d542-4e68-a7fd-a1f51a3dd307 # Assets
handle: responsiveImage
instructions: 'Switch between image assets depending on the aspect ratio of the browser.  Typically, this is used to supply separate desktop (landscape) and mobile (portrait) images.  To use a single image for all cases, just upload a single image to either field.'
name: 'Responsive Image'
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 1435764300
  columns:
    __assoc__:
      -
        - de97ce0f-548b-4114-8d77-fbf9a3b6c2c2 # Landscape Browser
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 87d83354-b0a5-4892-bca2-8837f965151b # Portrait Browser
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_responsiveimage}}'
  fieldLayout: row
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: true
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
