contentColumnType: string
fieldGroup: 210b8f7a-99b9-43ab-baba-f8b9d773b1c1 # Layout
handle: spacing
instructions: ''
name: Spacing
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - 'Small (40px, separates units of same section)'
        -
          - value
          - s
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Medium (60px, separates similar sections)'
        -
          - value
          - m
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Large (120px, separates divergent sections)'
        -
          - value
          - l
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Extra Large (160px)'
        -
          - value
          - xl
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
