columnSuffix: vicmdhdp
contentColumnType: string
fieldGroup: 350f57c3-762b-4c5a-b36c-864cbe3f5e4f # Text
handle: textAlignment
instructions: ''
name: 'Text Alignment'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Left
        -
          - value
          - left
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Center
        -
          - value
          - center
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Right
        -
          - value
          - right
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
