contentColumnType: boolean
fieldGroup: 350f57c3-762b-4c5a-b36c-864cbe3f5e4f # Text
handle: unorphan
instructions: 'Prevent the last word of text from being on it''s own line using https://github.com/rstacruz/unorphan.'
name: Unorphan
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
