fieldLayouts:
  181bf758-8eb7-4719-a567-bd11a765719f:
    tabs:
      -
        elements:
          -
            style: tip
            tip: 'These values are used whenever SEO fields are left undefined on a page entry.'
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: ec56af06-33ca-4f16-a73a-89f37d116142 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: defaultSeo
name: 'Default SEO'
