#import "../fragments/blocks.gql"

fragment tower on towers_towers_Entry {
	id
	slug
	blocks { ...blocks }

	# metaTitle
	# metaDescription
	# metaImage { path }
	# robots
	# canonical: simpleText

}
