defaultPlacement: end
enableVersioning: true
handle: products
name: Products
previewTargets:
  -
    __assoc__:
      -
        - label
        - Prod
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - ''
propagationMethod: all
siteSettings:
  c669537f-8a7f-4bde-962a-2e61c9b653c2: # Site
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'products/{slug}'
structure:
  maxLevels: 1
  uid: ca429f94-adc9-4293-95ab-da84ad113e7a
type: structure
