defaultPlacement: end
enableVersioning: false
handle: redirects
name: Redirects
propagationMethod: all
siteSettings:
  008df272-719d-4314-91bd-46f97a05c1d7: # Site
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
