fieldLayouts:
  77b8a586-56a0-47c9-9e1c-1a0ab717dc97:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: assets
hasUrls: true
name: Assets
settings:
  bucket: $SPACES_BUCKET
  contentDisposition: ''
  endpoint: $SPACES_ENDPOINT
  expires: '1 years'
  keyId: $SPACES_API_KEY
  region: $SPACES_REGION
  secret: $SPACES_SECRET
  subfolder: cms
sortOrder: 0
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: vaersaagod\dospaces\Volume
url: '@spacesBaseUrl'
