childBlocks: ''
field: fd4326a9-8ced-46ef-b0f2-c283f7482614 # Blocks
fieldLayouts:
  c618c6a8-4ba3-44c6-b112-5edc91469e5f:
    tabs:
      -
        elements:
          -
            style: tip
            tip: 'Render a single media asset.'
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: d6a44fe4-1500-4868-8559-30fd3b34625e # Responsive Image
            instructions: ''
            label: Image
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2f43c4ca-6ee6-4e49-9dc2-286e151ea6b0 # Responsive Video
            instructions: ''
            label: Video
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2a3e1dff-e96a-4ac1-8a6e-7eed68dfaa4e # Max Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: mediaAsset
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Media Asset'
sortOrder: 3
topLevel: true
