childBlocks: null
conditions: null
description: null
enabled: true
field: 2fd34dec-1616-4dfa-a937-862dd23bb8ed # Blocks
fieldLayouts:
  abba5dc6-7f14-4408-8a79-5d803019b134:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            style: tip
            tip: 'A simple, text-only Marquee.'
            type: craft\fieldlayoutelements\Tip
            uid: 1a927204-c414-485f-b760-dd52e11e9932
            userCondition: null
          -
            elementCondition: null
            fieldUid: ca292f2e-a489-4abf-8bfd-a37201b553c2 # Full WYSIWYG
            instructions: null
            label: Copy
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 958043b8-20f4-4ec0-809a-c0d9b90742ac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: acc3eb47-55fc-4174-9a80-46bbd841f2d9 # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a87cb2b-fb17-46e3-9f31-64e14a978af2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 15e25a99-4504-441a-83fe-1a4043214d29
        userCondition: null
group: null
groupChildBlockTypes: true
handle: simpleMarquee
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Simple Marquee'
sortOrder: 9
topLevel: true
