childBlocks: ''
field: fd4326a9-8ced-46ef-b0f2-c283f7482614 # Blocks
fieldLayouts:
  c1966eaf-31ee-45a3-b760-92b32f4a0b56:
    tabs:
      -
        elements:
          -
            style: tip
            tip: 'A simple, text-only Marquee'
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: 1a4b6751-b39b-4889-a185-e55df4e88fdb # Text
            instructions: ''
            label: Title
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4231471d-4063-4b18-a8b0-f8927cc22cb9 # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: simpleMarquee
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Simple Marquee'
sortOrder: 8
topLevel: true
