childBlocks: null
field: fd4326a9-8ced-46ef-b0f2-c283f7482614 # Blocks
fieldLayouts:
  a8109191-771f-4cb0-8e27-fcf9f66eb0a9:
    tabs:
      -
        elements:
          -
            style: tip
            tip: 'Adds vertical space between other blocks.'
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: f25955e8-9b37-4cf4-9101-2d6d2fa0a879 # Spacing
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: spacer
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Spacer
sortOrder: 5
topLevel: true
