childBlocks:
  - copy
  - mediaAsset
  - spacer
field: fd4326a9-8ced-46ef-b0f2-c283f7482614 # Blocks
fieldLayouts:
  234a0196-fce1-41c0-abc6-e685f4dd787d:
    tabs:
      -
        elements:
          -
            style: tip
            tip: 'Supports wrapping child blocks with a different background color.'
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: 51895965-9e46-40ff-a2a8-1f2ba17998db # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: wrapper
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Wrapper
sortOrder: 6
topLevel: true
