#import "@cloak-app/craft/queries/fragments/responsive-srcset.gql"
#import "@cloak-app/craft/queries/fragments/responsive-video.gql"

# Get list of blocks. This gets weird because you can't have recursion in gql
fragment blocks on NeoBlockInterface {

	# Recursive blocks
	...wrapperBlock

	# Reusable sections
	...reusableSectionBlock

	# The remainder of standard blocks
	...nonWrapperBlocks
}

# Wrapper block
fragment wrapperBlock on blocks_wrapper_BlockType {
	backgroundColor
	blocks: children {
		...nonWrapperBlocks
	}
}

# Reusable sections, only supports one level of depth
fragment reusableSectionBlock on blocks_reusableSection_BlockType {
	reusableSection {
		... on reusableSections_default_Entry {
			id
			blocks {
				...wrapperBlock
				...nonWrapperBlocks
			}
		}
	}
}

# The majority of blocks
fragment nonWrapperBlocks on NeoBlockInterface {
	id
	__typename

	# Copy
	... on blocks_copy_BlockType {
		content: fullWysiwyg
		balanceText
		unorphan
		textAlign: textAlignment
	}

	# Media
	... on blocks_mediaAsset_BlockType {
		image: responsiveImage { ... responsiveSrcset }
		video: responsiveVideo { ... responsiveVideo }
		maxWidth
	}

	# Simple marquee
	... on blocks_simpleMarquee_BlockType {
		copy: fullWysiwyg
		buttons {
			... on buttons_BlockType {
				id
				label
				to
			}
		}
	}

	# Spacer
	... on blocks_spacer_BlockType {
		height: spacing
	}
}
